package vn.edu.hcmus.student.sv19127584.Client;

import java.awt.*;

/**
 * vn.edu.hcmus.student.sv19127584.Client
 * Created by 19127584 - Mạch Cảnh Toàn
 * Date 1/15/2022 - 10:59 PM
 * Description: ...
 */
public class MenuAppChat extends javax.swing.JFrame {

    /**
     * Creates new form loginFrame
     */
    public MenuAppChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        bnLogin = new javax.swing.JButton();
        bnRegister = new javax.swing.JButton();
        lbAppChat = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bnLogin.setBackground(new java.awt.Color(51, 102, 255));
        bnLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bnLogin.setForeground(new java.awt.Color(255, 51, 51));
        bnLogin.setText("LOGIN");
        bnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnLoginActionPerformed(evt);
            }
        });

        bnRegister.setBackground(new java.awt.Color(51, 153, 255));
        bnRegister.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bnRegister.setForeground(new java.awt.Color(255, 0, 102));
        bnRegister.setText("REGISTER");
        bnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnRegisterActionPerformed(evt);
            }
        });

        lbAppChat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbAppChat.setForeground(new java.awt.Color(51, 153, 255));
        lbAppChat.setText("App Chat");

        lbExit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbExit.setText("Exit");
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbExit))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(98, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbAppChat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bnRegister))
                                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbAppChat)
                                .addGap(27, 27, 27)
                                .addComponent(bnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(lbExit))
        );

        pack();
    }// </editor-fold>

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void bnLoginActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new LoginAppChat().setVisible(true);
        dispose();
    }

    private void bnRegisterActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new RegisterAppChat().setVisible(true);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAppChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAppChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAppChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAppChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAppChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton bnLogin;
    private javax.swing.JButton bnRegister;
    private javax.swing.JLabel lbAppChat;
    private javax.swing.JLabel lbExit;
    // End of variables declaration
}